# Generated by Django 3.1.7 on 2021-03-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0003_auto_20210304_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transação',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
